#!/bin/bash

echo ~~~ setting up workplace ~~~

echo ~~~ upgrade bashrc ~~~
cat bashrc >> ~/.bashrc
echo ~~~ OK ~~~

echo ~~~ install pip ~~~
sudo apt -y install python-pip
echo ~~~ OK ~~~

echo ~~~ install vim ~~~
sudo apt -y install vim
echo ~~~ clone Vundle ~~~
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/Vundle.vim
echo ~~~ copy vimrc ~~~
cp vimrc ~/.vimrc
echo ~~~ copy colorscheme ~~~
cp colors ~/.vim -r
echo ~~~ copy ycm_extra_conf ~~~
cp ycm_extra_conf.py ~/.ycm_extra_conf.py
echo ~~~ set vim as global editor ~~~
export EDITOR=vim
echo ~~~ OK ~~~

echo ~~~ install clang-9 ~~~
curl -SL http://releases.llvm.org/9.0.0/clang%2bllvm-9.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz | tar -xJC .
mv clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04 clang_9.0.0
sudo mv clang_9.0.0 /usr/local
echo ~~~ OK ~~~

echo ~~~ setup clang-format ~~~
sudo apt -y install clang-format
cp clang-format.py ~/.vim/
cp clang-format.conf ~/.clang-format
echo ~~~ OK ~~~

echo ~~~ install python3 ~~~
sudo apt -y install python3
echo ~~~ OK ~~~

echo ~~~ install gcc ~~~
sudo apt -y install gcc
echo ~~~ OK ~~~

echo ~~~ install cmake ~~~
sudo apt -y install cmake
echo ~~~ OK ~~~

echo ~~~ install git ~~~
sudo apt -y install git
echo ~~~ install tig ~~~
sudo apt -y install tig
echo ~~~ copy gitconfig ~~~
cp gitconfig ~/.gitconfig
echo ~~~ OK ~~~

echo ~~~ install tmux ~~~
sudo apt -y install tmux
echo ~~~ copy tmuxconfig ~~~
cp tmux.conf ~/.tmux.conf
echo ~~~ install tmuxinator ~~~
sudo apt -y install tmuxinator
mkdir ~/.tmuxinator
cp -r tmuxinator/* ~/.tmuxinator/
echo ~~~ OK ~~~

echo ~~~ install thefuck ~~~
sudo -H pip install thefuck
echo ~~~ OK ~~~

echo ~~~ install tree ~~~
sudo apt -y install tree
echo ~~~ OK ~~~


echo ~~~ all what you need successfully installed ~~~
