#!/bin/bash

echo ~~~ setting up workplace ~~~

echo ~~~ install vim ~~~
sudo apt -y install vim
echo ~~~ clone Vundle ~~~
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/Vundle.vim
echo ~~~ copy vimrc ~~~
cp vimrc ~/.vimrc
export EDITOR=vim
echo ~~~ OK ~~~

echo ~~~ install python3 ~~~
sudo apt -y install python3
echo ~~~ OK ~~~

echo ~~~ install gcc ~~~
sudo apt -y install gcc
echo ~~~ OK ~~~

echo ~~~ install cmake ~~~
sudo apt -y install cmake
echo ~~~ OK ~~~

echo ~~~ install git ~~~
sudo apt -y install git
echo ~~~ install tig ~~~
sudo apt -y install tig
echo ~~~ copy gitconfig ~~~
cp gitconfig ~/.gitconfig
echo ~~~ OK ~~~

echo ~~~ install tmux ~~~
sudo apt -y install tmux
echo ~~~ copy tmuxconfig ~~~
cp tmux.conf ~/.tmux.conf
echo ~~~ install tmuxinator ~~~
sudo apt -y install tmuxinator
mkdir ~/.tmuxinator
cp -r tmuxinator/* ~/.tmuxinator/
echo ~~~ OK ~~~

echo ~~~ all what you need successfully installed ~~~
