#!/bin/bash

echo ~~~ setting up workplace ~~~

export HOMEBREW_NO_AUTO_UPDATE=1

echo ~~~ install vim ~~~
brew install vim
echo ~~~ clone Vundle ~~~
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/Vundle.vim
echo ~~~ copy vimrc ~~~
cp vimrc ~/.vimrc
export EDITOR=vim
echo ~~~ OK ~~~

echo ~~~ install python3 ~~~
brew install python3
echo ~~~ OK ~~~

echo ~~~ install gcc ~~~
brew install gcc
echo ~~~ OK ~~~

echo ~~~ install cmake ~~~
brew install cmake
echo ~~~ OK ~~~

echo ~~~ install git ~~~
brew install git
echo ~~~ install tig ~~~
brew install tig
echo ~~~ copy gitconfig ~~~
cp gitconfig ~/.gitconfig
echo ~~~ OK ~~~

echo ~~~ install tmux ~~~
brew install tmux
echo ~~~ copy tmuxconfig ~~~
cp tmux.conf ~/.tmux.conf
echo ~~~ install tmuxinator ~~~
brew install tmuxinator
mkdir ~/.tmuxinator
cp -r tmuxinator/* ~/.tmuxinator/
echo ~~~ OK ~~~

echo ~~~ all what you need successfully installed ~~~
